Doctors... #speaker:Ms. Pink #portrait:ms_pink_neutral #layout:right
All they care is about money and tricking folks into injecting "vAcCiNEs"...
These "vAcCiNEs" are just another way for the government to monitor us!
Just you wait...
I'll expose you!